build site:
  image: node:12
  stage: build
  script:
    - npm install 
    - npm run build
  artifacts:
    paths:
      - dist

test:
  image: node:12
  stage: test
  script:
    - npm install
    - npm run lint

pages:
  image: node:12
  stage: deploy
  script:
    - npm install --progress=false
    - npm run build
    - rm -rf public
    - mkdir public
    - cp -r dist/* public
  artifacts:
    expire_in: 1 day
    paths:
      - public
