build site:
  image: node:12
  stage: build
  script:
    - npm install 
    - npm run build
  artifacts:
    paths:
      - dist

test:
  image: node:12
  stage: test
  script:
    - npm install
    - npm run lint

pages:
  image: node:12
  stage: deploy
  script:
    - npm install --progress=false
    - npm run build
    - mv public public-vue # GitLab Pages hooks on the public folder
    - mv dist public 
  artifacts:
    paths:
      - public
  only:
    refs:
      - master
