// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AddSessionScreen: typeof import('./src/components/session-form/AddSessionScreen.vue')['default']
    AdminPanel: typeof import('./src/components/admin-panel/AdminPanel.vue')['default']
    AttendedData: typeof import('./src/components/user-profile/AttendedData.vue')['default']
    ContentContainer: typeof import('./src/components/ContentContainer.vue')['default']
    DetailView: typeof import('./src/components/details/DetailView.vue')['default']
    EditSessionScreen: typeof import('./src/components/session-form/EditSessionScreen.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTimeSelect: typeof import('element-plus/es')['ElTimeSelect']
    EventBody: typeof import('./src/components/event/EventBody.vue')['default']
    EventContainer: typeof import('./src/components/event/EventContainer.vue')['default']
    EventFooter: typeof import('./src/components/event/EventFooter.vue')['default']
    EventHeader: typeof import('./src/components/event/EventHeader.vue')['default']
    EventList: typeof import('./src/components/event/EventList.vue')['default']
    HeaderContainer: typeof import('./src/components/header/HeaderContainer.vue')['default']
    HeaderLogo: typeof import('./src/components/header/HeaderLogo.vue')['default']
    HeaderNav: typeof import('./src/components/header/HeaderNav.vue')['default']
    LoginForm: typeof import('./src/components/login/LoginForm.vue')['default']
    OrganizedData: typeof import('./src/components/user-profile/OrganizedData.vue')['default']
    Profile: typeof import('./src/components/user-profile/Profile.vue')['default']
    SessionForm: typeof import('./src/components/session-form/SessionForm.vue')['default']
    UpdateForm: typeof import('./src/components/user-profile/UpdateForm.vue')['default']
  }
}

export { }
