export const eventLabels = {
  name: "Tytuł sesji",
  game: "System/Świat",
  date: "Data",
  time: "Godzina",
  triggers: "Triggery",
  safety_tools: "Narzędzia bezpieczeństwa",
  freePlaces: "Wolnych miejsc",
  maximalCount: "Maksymalna liczba uczestników",
  description: "Opis sesji",
  displayName: "MG",
  isNewbieFriendly: "Przyjazne dla początkujących",
  isSettingFamiliarityRequired: "Wymagana znajomość settingu",
  isCameraRequired: "Wymagana kamera",
  userPreparation: "Przygotowanie uczestników",
};
