export const SessionForm = {
  mail: "",
  fullName: "",
  discord: "",
  roll20Mail: "",
  phone: "",
  displayName: "",
  organization: "",
  title: "",
  description: "",
  game: "",
  tags: [""],
  triggers: [""],
  safetyTools: [""],
  minimalCount: 3,
  maximalCount: 3,
  isNewbieFriendly: false,
  isSettingFamiliarityRequired: false,
  isCameraRequired: false,
  userPreparation: "",
  date: "",
  time: "",
  other: "",
  toolsPreference: "",
};
