export const SessionDetails = {
  displayName: "",
  organization: "",
  title: "",
  description: "",
  game: "",
  tags: [""],
  triggers: [""],
  safetyTools: [""],
  minimalCount: 3,
  maximalCount: 3,
  isNewbieFriendly: false,
  isSettingFamiliarityRequired: false,
  isCameraRequired: false,
  userPreparation: "",
  date: "",
  time: "",
  freePlaces: 3,
  id: 0,
};
